### ISSUE TITLE
cl-arrows is proprietary software

### ISSUE THREAD

**Issue by phoe** [fisxoj/sanity-clause#27]
cl-arrows [does not have a license file](https://github.com/nightfly19/cl-arrows/issues/5) which makes it proprietary software.

Consider switching to another arrow macro library, such as [arrows](https://github.com/Harleqin/arrows), [arrow-macros](https://github.com/hipeta/arrow-macros), or (shameless plug) [binding-arrows](https://github.com/phoe/binding-arrows).

**Comment by rwiker** [comment]
cl-arrows has been removed from quicklisp, and since sanity-clause uses cl-arrows, it has also been removed. I did a quick check substituting "arrows" for "cl-arrows", and it seems to work. I'd be happy to provide a pull request, but one of the other alternatives may be preferred.

**Comment by phoe** [comment]
I think arrows is good and should work.

**Comment by fisxoj** [comment]
Thanks for bringing this up and sorry it's taken so long to address it.  I wanted to spend a little time looking at the differences between the libraries suggested, but apparently I don't have time for that, so I'll use `arrows` for now, at least.

**Comment by phoe** [comment]
No problem - `arrows` should work out of the box. It seems that `sanity-clause` has been dropped off Quicklisp because of this; you might want to readd it there.

**Comment by fisxoj** [comment]
Asked to be reinstated on quicklisp-projects here: https://github.com/quicklisp/quicklisp-projects/issues/1990
